version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: test_postgres
    environment:
      - ConnectionStrings__Default=Host=db;Port=5432;Database=testdb;Username=postgres;Password=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@test.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata:
